In [120]:
from scipy.io import loadmat
import os
import numpy as np
import h5py
import torch
dir_path="/home/amos/haitun/pycode/"#os.path.dirname(os.path.abspath())

# Open the MATLAB v7.3 file using h5py
dataset = h5py.File(os.path.join(dir_path,'source/matlab/savedData.mat'), 'r')

# Read the dataset from the file
sample_list = dataset['sample_list']
for samples_ref in sample_list[0]:
    dataset[samples_ref]

dataset[samples_ref]
# dataset_list = torch.tensor(dataset[:])
# # Close the file
# mat_file.close()

# np.array(dataset_list[0][0])

<HDF5 dataset "b": shape (1, 234), type "|O">
<HDF5 dataset "CA": shape (1, 175), type "|O">
<HDF5 dataset "oU": shape (1, 238), type "|O">
<HDF5 dataset "hlb": shape (1, 114), type "|O">
<HDF5 dataset "ayb": shape (1, 178), type "|O">
<HDF5 dataset "hSb": shape (1, 47), type "|O">
<HDF5 dataset "BXb": shape (1, 190), type "|O">
<HDF5 dataset "5ic": shape (1, 170), type "|O">
<HDF5 dataset "hCc": shape (1, 171), type "|O">
<HDF5 dataset "BVc": shape (1, 36), type "|O">
<HDF5 dataset "GZc": shape (1, 232), type "|O">
<HDF5 dataset "Tpd": shape (1, 198), type "|O">
<HDF5 dataset "gMd": shape (1, 36), type "|O">
<HDF5 dataset "lQd": shape (1, 247), type "|O">


<HDF5 dataset "lQd": shape (1, 247), type "|O">

In [74]:
print(dataset.size)

14


KeyError: 'trajectory_list'

In [56]:
np.save("test.npy",dataframe)

NameError: name 'np' is not defined

In [4]:
import numpy as np
import aeon
X=np.ones([5,6,7])
aeon.utils

<module 'aeon.utils' from '/home/amos/anaconda3/envs/haitun/lib/python3.8/site-packages/aeon/utils/__init__.py'>

In [7]:
from aeon.transformations.collection import DWTTransformer
import numpy as np
data = np.array([[[1,2,3,4,5,6,7,8,9,10]],[[5,5,5,5,5,5,5,5,5,5]]])
dwt = DWTTransformer(n_levels=20)
data2 = dwt.fit_transform(data)
data2.shape

(2, 1, 26)

In [2]:
import torch
import time

def _kinetic_feature(single_sample):
    # 在这加入到你的计算逻辑
    result = single_sample ** 2
    # 假设这个过程非常的费时
    time.sleep(2)  
    return result

def parallel_execution(samples):
    streams = []
    results = []
    # 创建一个CUDA流来为每个样本运行_kinetic_feature函数
    for i in range(len(samples)):
        streams.append(torch.cuda.Stream())
        
    for i, sample in enumerate(samples):
        with torch.cuda.stream(streams[i]):
            result = _kinetic_feature(sample)
            results.append(result)
            
    # 等待所有流的操作完成
    for i in range(len(samples)):
        torch.cuda.current_stream().wait_stream(streams[i])
    
    return results

cuda_samples = [torch.tensor(i, device='cuda') for i in range(10)]
results = parallel_execution(cuda_samples)

# 打印结果
for result in results:
    print(result)

tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(4, device='cuda:0')
tensor(9, device='cuda:0')
tensor(16, device='cuda:0')
tensor(25, device='cuda:0')
tensor(36, device='cuda:0')
tensor(49, device='cuda:0')
tensor(64, device='cuda:0')
tensor(81, device='cuda:0')


In [7]:
import torch
from torch.nn.utils.rnn import pad_sequence
from operator import itemgetter 

# 假设我们有以下tensor列表以及对应的index
tensors = [torch.randn(50), torch.randn(100), torch.randn(150), torch.randn(50), torch.randn(100)]
tensor_lengths = [len(t) for t in tensors]
tensor_indices = list(range(len(tensors)))

# 将上述列表合并为一个列表并按照length排序
length_index_tensors = sorted(zip(tensor_lengths, tensor_indices, tensors), key=itemgetter(0))

length_index_tensors

[(50,
  0,
  tensor([-1.6923, -0.1544,  1.9792, -1.0376,  0.4598,  0.9939, -0.4259,  0.3254,
          -1.0183, -0.6959,  1.8755, -0.2923,  0.1903,  1.9563,  0.2392,  0.6282,
           0.4556,  2.2616,  0.5598, -0.1053,  0.0183,  1.8638,  1.7166, -1.6367,
          -0.2212, -1.1999, -0.2649, -1.5602,  0.1270, -1.1239, -2.0969, -0.5352,
           0.0666,  0.7322,  0.3686,  0.1283, -1.3826,  1.7035, -0.0280,  0.3705,
           0.2679,  3.4676, -0.0299, -0.8803,  0.2812, -0.3721,  0.1177, -2.5318,
           0.1107,  1.4310])),
 (50,
  3,
  tensor([ 0.3066, -0.6730, -0.4274,  1.5191,  0.9963,  0.8142, -1.2502,  1.7890,
           0.9502, -0.9045, -0.1636,  0.9384,  0.8782,  1.8705, -1.0843, -0.2210,
          -0.5122,  0.6798, -0.0990, -2.7825,  0.1450,  1.6235,  0.4835, -1.0989,
          -0.1385,  1.5020,  0.6848, -0.7145, -0.3568, -0.6627, -2.4854,  0.2502,
           1.0837,  0.6952,  0.5972, -0.7339, -0.7667,  0.6331,  3.2073, -0.5579,
           0.4174,  1.5318, -0.9855,  1.0638,

In [9]:
# 将同样长度的tensor分别组装为batch
batches = []
current_length = length_index_tensors[0][0]
current_batch_indices = []
current_batch_tensors = []
for length, index, tensor in length_index_tensors:
    if length != current_length:
        batches.append((current_length, current_batch_indices, current_batch_tensors))
        current_length = length
        current_batch_indices = []
        current_batch_tensors = []
    current_batch_indices.append(index)
    current_batch_tensors.append(tensor)
batches.append((current_length, current_batch_indices, current_batch_tensors))

batches

[(50,
  [0, 3],
  [tensor([-1.6923, -0.1544,  1.9792, -1.0376,  0.4598,  0.9939, -0.4259,  0.3254,
           -1.0183, -0.6959,  1.8755, -0.2923,  0.1903,  1.9563,  0.2392,  0.6282,
            0.4556,  2.2616,  0.5598, -0.1053,  0.0183,  1.8638,  1.7166, -1.6367,
           -0.2212, -1.1999, -0.2649, -1.5602,  0.1270, -1.1239, -2.0969, -0.5352,
            0.0666,  0.7322,  0.3686,  0.1283, -1.3826,  1.7035, -0.0280,  0.3705,
            0.2679,  3.4676, -0.0299, -0.8803,  0.2812, -0.3721,  0.1177, -2.5318,
            0.1107,  1.4310]),
   tensor([ 0.3066, -0.6730, -0.4274,  1.5191,  0.9963,  0.8142, -1.2502,  1.7890,
            0.9502, -0.9045, -0.1636,  0.9384,  0.8782,  1.8705, -1.0843, -0.2210,
           -0.5122,  0.6798, -0.0990, -2.7825,  0.1450,  1.6235,  0.4835, -1.0989,
           -0.1385,  1.5020,  0.6848, -0.7145, -0.3568, -0.6627, -2.4854,  0.2502,
            1.0837,  0.6952,  0.5972, -0.7339, -0.7667,  0.6331,  3.2073, -0.5579,
            0.4174,  1.5318, -0.9855,  1

In [ ]:
# 执行计算，这里的model可以替换为任何接受tensor输入，并且输出tensor的模型
model = lambda x: x.sum(dim=0)
outputs = []
for length, indices, batch in batches:
    batch_output = model(batch)
    outputs.extend(zip(indices, batch_output))

# 根据index对计算结果进行排序
outputs.sort(key=itemgetter(0))
final_outputs = [output for index, output in outputs]